# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  adapter: postgresql
  encoding: unicode
  host: ep-tight-heart-a8j596p3-pooler.eastus2.azure.neon.tech
  port: 5432
  database: neondb
  username: neondb_owner
  password: npg_YsuFW7E3jdtO
  pool: 5
  sslmode: require
  schema_search_path: "public"


test:
  <<: *default
  database: fullstack_test_api_test

production:
  primary: &primary_production
    <<: *default
    database: fullstack_test_api_production
    username: fullstack_test_api
    password: <%= ENV["FULLSTACK_TEST_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: fullstack_test_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: fullstack_test_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: fullstack_test_api_production_cable
    migrations_paths: db/cable_migrate
